/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[17];

//Textdraws
PublicTD[0] = TextDrawCreate(322.000000, 193.000000, "_");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.600000, 16.250001);
TextDrawTextSize(PublicTD[0], 305.500000, 209.500000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 2);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 1296911871);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(223.000000, 332.000000, "ld_beat:chit");
TextDrawFont(PublicTD[1], 4);
TextDrawLetterSize(PublicTD[1], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[1], 8.500000, -10.500000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], 1296911871);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 1);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(322.000000, 196.000000, "_");
TextDrawFont(PublicTD[2], 1);
TextDrawLetterSize(PublicTD[2], 0.600000, -0.299997);
TextDrawTextSize(PublicTD[2], 224.500000, 206.500000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 2);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 65535);
TextDrawUseBox(PublicTD[2], 1);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);

PublicTD[3] = TextDrawCreate(219.000000, 200.000000, "Preview_Model");
TextDrawFont(PublicTD[3], 5);
TextDrawLetterSize(PublicTD[3], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[3], 66.000000, 69.000000);
TextDrawSetOutline(PublicTD[3], 0);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 1);
TextDrawColor(PublicTD[3], -1);
TextDrawBackgroundColor(PublicTD[3], -1061109505);
TextDrawBoxColor(PublicTD[3], -1061109760);
TextDrawUseBox(PublicTD[3], 0);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 0);
TextDrawSetPreviewModel(PublicTD[3], 0);
TextDrawSetPreviewRot(PublicTD[3], -10.000000, 0.000000, -20.000000, 1.000000);
TextDrawSetPreviewVehCol(PublicTD[3], 1, 1);

PublicTD[4] = TextDrawCreate(291.000000, 203.000000, "Name:");
TextDrawFont(PublicTD[4], 1);
TextDrawLetterSize(PublicTD[4], 0.429166, 1.500000);
TextDrawTextSize(PublicTD[4], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[4], 1);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 1);
TextDrawColor(PublicTD[4], -1);
TextDrawBackgroundColor(PublicTD[4], 255);
TextDrawBoxColor(PublicTD[4], 50);
TextDrawUseBox(PublicTD[4], 0);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 0);

PublicTD[5] = TextDrawCreate(338.000000, 202.000000, "Hellstone_Rodriguez");
TextDrawFont(PublicTD[5], 1);
TextDrawLetterSize(PublicTD[5], 0.270833, 1.699999);
TextDrawTextSize(PublicTD[5], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[5], 1);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 1);
TextDrawColor(PublicTD[5], -1);
TextDrawBackgroundColor(PublicTD[5], 255);
TextDrawBoxColor(PublicTD[5], 50);
TextDrawUseBox(PublicTD[5], 0);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 0);

PublicTD[6] = TextDrawCreate(292.000000, 223.000000, "Age:");
TextDrawFont(PublicTD[6], 1);
TextDrawLetterSize(PublicTD[6], 0.533333, 1.450000);
TextDrawTextSize(PublicTD[6], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[6], 1);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 1);
TextDrawColor(PublicTD[6], -1);
TextDrawBackgroundColor(PublicTD[6], 255);
TextDrawBoxColor(PublicTD[6], 50);
TextDrawUseBox(PublicTD[6], 0);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 0);

PublicTD[7] = TextDrawCreate(339.000000, 221.000000, "12");
TextDrawFont(PublicTD[7], 1);
TextDrawLetterSize(PublicTD[7], 0.600000, 1.800000);
TextDrawTextSize(PublicTD[7], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[7], 1);
TextDrawSetShadow(PublicTD[7], 0);
TextDrawAlignment(PublicTD[7], 1);
TextDrawColor(PublicTD[7], -1);
TextDrawBackgroundColor(PublicTD[7], 255);
TextDrawBoxColor(PublicTD[7], 50);
TextDrawUseBox(PublicTD[7], 0);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 0);

PublicTD[8] = TextDrawCreate(292.000000, 239.000000, "Sex:");
TextDrawFont(PublicTD[8], 1);
TextDrawLetterSize(PublicTD[8], 0.475000, 1.750000);
TextDrawTextSize(PublicTD[8], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[8], 1);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 1);
TextDrawColor(PublicTD[8], -1);
TextDrawBackgroundColor(PublicTD[8], 255);
TextDrawBoxColor(PublicTD[8], 50);
TextDrawUseBox(PublicTD[8], 0);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 0);

PublicTD[9] = TextDrawCreate(329.000000, 240.000000, "Mamrobiti");
TextDrawFont(PublicTD[9], 1);
TextDrawLetterSize(PublicTD[9], 0.579166, 1.700000);
TextDrawTextSize(PublicTD[9], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[9], 1);
TextDrawSetShadow(PublicTD[9], 0);
TextDrawAlignment(PublicTD[9], 1);
TextDrawColor(PublicTD[9], -1);
TextDrawBackgroundColor(PublicTD[9], 255);
TextDrawBoxColor(PublicTD[9], 50);
TextDrawUseBox(PublicTD[9], 0);
TextDrawSetProportional(PublicTD[9], 1);
TextDrawSetSelectable(PublicTD[9], 0);

PublicTD[10] = TextDrawCreate(217.000000, 269.000000, "Personal ID:");
TextDrawFont(PublicTD[10], 1);
TextDrawLetterSize(PublicTD[10], 0.416666, 1.450000);
TextDrawTextSize(PublicTD[10], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[10], 1);
TextDrawSetShadow(PublicTD[10], 0);
TextDrawAlignment(PublicTD[10], 1);
TextDrawColor(PublicTD[10], -1);
TextDrawBackgroundColor(PublicTD[10], 255);
TextDrawBoxColor(PublicTD[10], 50);
TextDrawUseBox(PublicTD[10], 0);
TextDrawSetProportional(PublicTD[10], 1);
TextDrawSetSelectable(PublicTD[10], 0);

PublicTD[11] = TextDrawCreate(298.000000, 268.000000, "12341");
TextDrawFont(PublicTD[11], 1);
TextDrawLetterSize(PublicTD[11], 0.600000, 1.750000);
TextDrawTextSize(PublicTD[11], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[11], 1);
TextDrawSetShadow(PublicTD[11], 0);
TextDrawAlignment(PublicTD[11], 1);
TextDrawColor(PublicTD[11], -1);
TextDrawBackgroundColor(PublicTD[11], 255);
TextDrawBoxColor(PublicTD[11], 50);
TextDrawUseBox(PublicTD[11], 0);
TextDrawSetProportional(PublicTD[11], 1);
TextDrawSetSelectable(PublicTD[11], 0);

PublicTD[12] = TextDrawCreate(219.000000, 283.000000, "Pasporti Gacemulia Los Santos Meriis Mier");
TextDrawFont(PublicTD[12], 1);
TextDrawLetterSize(PublicTD[12], 0.233333, 1.750000);
TextDrawTextSize(PublicTD[12], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[12], 1);
TextDrawSetShadow(PublicTD[12], 0);
TextDrawAlignment(PublicTD[12], 1);
TextDrawColor(PublicTD[12], -1);
TextDrawBackgroundColor(PublicTD[12], 255);
TextDrawBoxColor(PublicTD[12], 50);
TextDrawUseBox(PublicTD[12], 0);
TextDrawSetProportional(PublicTD[12], 1);
TextDrawSetSelectable(PublicTD[12], 0);

PublicTD[13] = TextDrawCreate(279.000000, 317.000000, "Daxurva");
TextDrawFont(PublicTD[13], 1);
TextDrawLetterSize(PublicTD[13], 0.579166, 1.450000);
TextDrawTextSize(PublicTD[13], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[13], 1);
TextDrawSetShadow(PublicTD[13], 0);
TextDrawAlignment(PublicTD[13], 1);
TextDrawColor(PublicTD[13], -1);
TextDrawBackgroundColor(PublicTD[13], 255);
TextDrawBoxColor(PublicTD[13], 50);
TextDrawUseBox(PublicTD[13], 0);
TextDrawSetProportional(PublicTD[13], 1);
TextDrawSetSelectable(PublicTD[13], 1);

PublicTD[14] = TextDrawCreate(317.000000, 318.000000, "_");
TextDrawFont(PublicTD[14], 1);
TextDrawLetterSize(PublicTD[14], 0.600000, 1.500004);
TextDrawTextSize(PublicTD[14], 295.000000, 89.000000);
TextDrawSetOutline(PublicTD[14], 1);
TextDrawSetShadow(PublicTD[14], 0);
TextDrawAlignment(PublicTD[14], 2);
TextDrawColor(PublicTD[14], -1);
TextDrawBackgroundColor(PublicTD[14], 255);
TextDrawBoxColor(PublicTD[14], -1061109505);
TextDrawUseBox(PublicTD[14], 1);
TextDrawSetProportional(PublicTD[14], 1);
TextDrawSetSelectable(PublicTD[14], 0);

PublicTD[15] = TextDrawCreate(262.000000, 312.000000, "ld_beat:chit");
TextDrawFont(PublicTD[15], 4);
TextDrawLetterSize(PublicTD[15], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[15], 17.000000, 26.000000);
TextDrawSetOutline(PublicTD[15], 1);
TextDrawSetShadow(PublicTD[15], 0);
TextDrawAlignment(PublicTD[15], 1);
TextDrawColor(PublicTD[15], -1061109505);
TextDrawBackgroundColor(PublicTD[15], -1061109505);
TextDrawBoxColor(PublicTD[15], -1061109710);
TextDrawUseBox(PublicTD[15], 1);
TextDrawSetProportional(PublicTD[15], 1);
TextDrawSetSelectable(PublicTD[15], 0);

PublicTD[16] = TextDrawCreate(355.000000, 312.000000, "ld_beat:chit");
TextDrawFont(PublicTD[16], 4);
TextDrawLetterSize(PublicTD[16], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[16], 17.000000, 26.000000);
TextDrawSetOutline(PublicTD[16], 1);
TextDrawSetShadow(PublicTD[16], 0);
TextDrawAlignment(PublicTD[16], 1);
TextDrawColor(PublicTD[16], -1061109505);
TextDrawBackgroundColor(PublicTD[16], -1061109505);
TextDrawBoxColor(PublicTD[16], -1061109710);
TextDrawUseBox(PublicTD[16], 1);
TextDrawSetProportional(PublicTD[16], 1);
TextDrawSetSelectable(PublicTD[16], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
